server:
  port: 8001

spring:
  application:
    name: cloud-payment-hystrix-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/mysqlceshi?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password:

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.erge.springcloud.entities

eureka:
  client:
    fetch-registry: true #不检索服务
    register-with-eureka: true #不向注册中心注册自己
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id:  payment8001   #设置显示的服务名
    prefer-ip-address: true      #设置是否显示ip地址
    lease-renewal-interval-in-seconds: 1 #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认是30秒）
    lease-expiration-duration-in-seconds: 2 #Eureka服务端在收到最后一次心跳后等待时间上限，单位为秒（默认是90秒），超时将剔除服务
#  server:
#    enable-self-preservation: false # 关闭自我保护
#    eviction-interval-timer-in-ms: 5000 # 每隔5秒进行一次服务列表清理